Repository Late-Night-Restaurant/backend, pull requests merged in 2023-01, with the labels that each got.

#4 [ Feat ] user profile exception
  src/main/java/com/backend/simya/domain/jwt/service/AuthService.java
  src/main/java/com/backend/simya/domain/jwt/service/TokenProvider.java
  src/main/java/com/backend/simya/domain/profile/controller/ProfileController.java
  src/main/java/com/backend/simya/domain/profile/dto/request/ProfileRequestDto.java
  src/main/java/com/backend/simya/domain/profile/entity/Profile.java
  src/main/java/com/backend/simya/domain/profile/service/ProfileService.java
  src/main/java/com/backend/simya/domain/user/controller/OauthController.java
  src/main/java/com/backend/simya/domain/user/controller/UserController.java
  src/main/java/com/backend/simya/domain/user/dto/request/LoginDto.java
  src/main/java/com/backend/simya/domain/user/dto/request/UserDto.java
  src/main/java/com/backend/simya/domain/user/entity/User.java
  src/main/java/com/backend/simya/domain/user/service/UserService.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
  src/main/java/com/backend/simya/global/common/ValidErrorDetails.java
Labels: feature, 쭈니

#7 [ Feat ] profile user relation
  src/main/java/com/backend/simya/domain/profile/controller/ProfileController.java
  src/main/java/com/backend/simya/domain/profile/dto/request/ProfileRequestDto.java
  src/main/java/com/backend/simya/domain/profile/dto/response/ProfileResponseDto.java
  src/main/java/com/backend/simya/domain/profile/entity/Profile.java
  src/main/java/com/backend/simya/domain/profile/service/ProfileService.java
  src/main/java/com/backend/simya/domain/user/controller/UserController.java
  src/main/java/com/backend/simya/domain/user/dto/request/UserDto.java
  src/main/java/com/backend/simya/domain/user/entity/User.java
  src/main/java/com/backend/simya/domain/user/service/OauthService.java
  src/main/java/com/backend/simya/domain/user/service/UserService.java
  src/main/java/com/backend/simya/global/common/BaseResponse.java
Labels: refactor, feature, 쭈니

#10 [ Feat ] #3 review
  src/main/java/com/backend/simya/domain/chattingroom/entity/ChattingRoom.java
  src/main/java/com/backend/simya/domain/profile/entity/Profile.java
  src/main/java/com/backend/simya/domain/profile/repository/ProfileRepository.java
  src/main/java/com/backend/simya/domain/review/controller/ReviewController.java
  src/main/java/com/backend/simya/domain/review/dto/ReviewRequestDto.java
  src/main/java/com/backend/simya/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/backend/simya/domain/review/entity/Review.java
  src/main/java/com/backend/simya/domain/review/repository/ReviewRepository.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
  src/main/java/com/backend/simya/domain/user/entity/User.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
Labels: feature, 왁

#13 [ feat ] Header 값 수정
  src/main/java/com/backend/simya/domain/jwt/service/AuthService.java
  src/main/java/com/backend/simya/domain/user/controller/UserController.java
  src/main/java/com/backend/simya/domain/user/dto/request/LoginDto.java
  src/main/java/com/backend/simya/global/config/SecurityConfig.java
  src/main/java/com/backend/simya/global/config/jwt/JwtFilter.java
  src/main/java/com/backend/simya/global/util/SecurityUtil.java
  src/test/java/com/backend/simya/domain/profile/service/ProfileServiceTest.java
Labels: refactor, 왁, 쭈니

#15 Feat/#14 get review
  src/main/java/com/backend/simya/domain/house/entity/House.java
  src/main/java/com/backend/simya/domain/review/controller/ReviewController.java
  src/main/java/com/backend/simya/domain/review/entity/Review.java
  src/main/java/com/backend/simya/domain/review/repository/ReviewRepository.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
Labels: refactor, feature, 왁

#17 [ Fix ] #6 refresh token reissue
  src/main/java/com/backend/simya/domain/house/service/TopicService.java
  src/main/java/com/backend/simya/domain/jwt/controller/AuthController.java
  src/main/java/com/backend/simya/domain/jwt/service/AuthService.java
  src/main/java/com/backend/simya/domain/jwt/service/TokenProvider.java
  src/main/java/com/backend/simya/domain/profile/entity/Profile.java
  src/main/java/com/backend/simya/domain/review/controller/ReviewController.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
  src/main/java/com/backend/simya/domain/user/entity/User.java
Labels: fix, 쭈니

#18 [ Feat ] #16 favorite
  src/main/java/com/backend/simya/domain/favorite/controller/FavoriteController.java
  src/main/java/com/backend/simya/domain/favorite/dto/MyFavoriteHouseResponseDto.java
  src/main/java/com/backend/simya/domain/favorite/entity/Favorite.java
  src/main/java/com/backend/simya/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/backend/simya/domain/favorite/service/FavoriteService.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseIntroductionResponseDto.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseResponseDto.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseShowResponseDto.java
  src/main/java/com/backend/simya/domain/house/entity/House.java
  src/main/java/com/backend/simya/domain/house/service/HouseService.java
  src/main/java/com/backend/simya/domain/profile/dto/response/ProfileResponseDto.java
  src/main/java/com/backend/simya/domain/profile/entity/Profile.java
  src/main/java/com/backend/simya/domain/profile/service/ProfileService.java
  src/main/java/com/backend/simya/domain/review/controller/ReviewController.java
  src/main/java/com/backend/simya/domain/review/dto/MyReviewResponseDto.java
  src/main/java/com/backend/simya/domain/review/dto/ReviewResponseDto.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
Labels: feature, 왁

#20 [ Refactor ] enum 형식 수정 및 dto 수정
  src/main/java/com/backend/simya/domain/house/controller/HouseController.java
  src/main/java/com/backend/simya/domain/house/dto/request/HouseOpenRequestDto.java
  src/main/java/com/backend/simya/domain/house/dto/request/HouseRequestDto.java
  src/main/java/com/backend/simya/domain/house/dto/request/HouseUpdateRequestDto.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseResponseDto.java
  src/main/java/com/backend/simya/domain/house/entity/Category.java
  src/main/java/com/backend/simya/domain/house/entity/House.java
  src/main/java/com/backend/simya/domain/house/repository/TopicRepository.java
  src/main/java/com/backend/simya/domain/house/service/HouseService.java
  src/main/java/com/backend/simya/domain/house/service/TopicService.java
  src/main/java/com/backend/simya/domain/profile/controller/ProfileController.java
  src/main/java/com/backend/simya/domain/profile/service/ProfileService.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
Labels: refactor, 채니

#22 [Feat ]# 19 house api
  src/main/java/com/backend/simya/domain/favorite/controller/FavoriteController.java
  src/main/java/com/backend/simya/domain/house/controller/HouseController.java
  src/main/java/com/backend/simya/domain/house/dto/request/HouseOpenRequestDto.java
  src/main/java/com/backend/simya/domain/house/dto/request/NewHouseRequestDto.java
  src/main/java/com/backend/simya/domain/house/dto/request/TopicRequestDto.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseShowResponseDto.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseSignboardResponseDto.java
  src/main/java/com/backend/simya/domain/house/dto/response/TopicResponseDto.java
  src/main/java/com/backend/simya/domain/house/entity/House.java
  src/main/java/com/backend/simya/domain/house/entity/Topic.java
  src/main/java/com/backend/simya/domain/house/repository/HouseRepository.java
  src/main/java/com/backend/simya/domain/house/service/HouseService.java
  src/main/java/com/backend/simya/domain/house/service/TopicService.java
  src/main/java/com/backend/simya/domain/jwt/service/TokenProvider.java
  src/main/java/com/backend/simya/domain/profile/service/ProfileService.java
  src/main/java/com/backend/simya/domain/review/controller/ReviewController.java
  src/main/java/com/backend/simya/domain/review/repository/ReviewRepository.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
Labels: feature, 왁

#24 [ Feat] 이야기 집 전문 메뉴 수정하기
  src/main/java/com/backend/simya/domain/house/controller/HouseController.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseShowResponseDto.java
  src/main/java/com/backend/simya/domain/house/entity/House.java
  src/main/java/com/backend/simya/domain/house/service/HouseService.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
Labels: feature, 채니

#27 [ refactor ] 이야기 집 API 리팩토링
  src/main/java/com/backend/simya/domain/house/controller/HouseController.java
  src/main/java/com/backend/simya/domain/house/dto/response/HouseIntroductionResponseDto.java
  src/main/java/com/backend/simya/domain/house/entity/House.java
  src/main/java/com/backend/simya/domain/house/service/HouseService.java
  src/main/java/com/backend/simya/domain/profile/repository/ProfileRepository.java
  src/main/java/com/backend/simya/domain/review/repository/ReviewRepository.java
  src/main/java/com/backend/simya/domain/review/service/ReviewService.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
Labels: refactor, 왁

#39 Feat/#38 websocket header
  src/main/java/com/backend/simya/domain/chat/controller/ChatController.java
  src/main/java/com/backend/simya/domain/chat/controller/ChatRoomController.java
  src/main/java/com/backend/simya/domain/chat/service/ChatService.java
  src/main/java/com/backend/simya/domain/jwt/service/TokenProvider.java
  src/main/java/com/backend/simya/domain/user/service/UserService.java
  src/main/java/com/backend/simya/global/config/SecurityConfig.java
  src/main/java/com/backend/simya/global/config/jwt/JwtFilter.java
  src/main/java/com/backend/simya/global/config/websocket/handler/StompHandler.java
  src/main/resources/templates/chat/roomdetail.ftl
Labels: refactor, feature, 쭈니

#42 [ Refactor ]#41 exception handling custom
  src/main/java/com/backend/simya/domain/chat/controller/ChatController.java
  src/main/java/com/backend/simya/domain/chat/controller/ChatRoomController.java
  src/main/java/com/backend/simya/domain/chat/controller/IndexController.java
  src/main/java/com/backend/simya/domain/chat/dto/ChatRoomDto.java
  src/main/java/com/backend/simya/domain/chat/service/RedisSubscriber.java
  src/main/java/com/backend/simya/domain/profile/controller/ProfileController.java
  src/main/java/com/backend/simya/domain/user/controller/UserController.java
  src/main/java/com/backend/simya/global/common/BaseResponseStatus.java
  src/main/java/com/backend/simya/global/config/SecurityConfig.java
  src/main/java/com/backend/simya/global/config/websocket/WebSockConfig.java
  src/main/java/com/backend/simya/global/config/websocket/handler/StompHandler.java
  src/main/resources/templates/chat/room.ftl
  src/main/resources/templates/chat/roomdetail.ftl
Labels: refactor, feature, 쭈니

#48 [ Feat ] #47 new class for android
  src/main/java/com/backend/simya/domain/chat/dto/ChatMessageForAndroid.java
  src/main/java/com/backend/simya/domain/chat/dto/ChatRoomForAndroid.java
  src/main/java/com/backend/simya/domain/chat/dto/ChatRoomInterface.java
  src/main/java/com/backend/simya/domain/chat/repository/ChatRoomRepositoryForAndroid.java
  src/main/java/com/backend/simya/domain/chat/service/ChatServiceForAndroid.java
  src/main/java/com/backend/simya/domain/house/controller/HouseController.java
  src/main/java/com/backend/simya/global/config/websocket/handler/StompHandlerForAndroid.java
Labels: feature, 왁

#51 [ Feat ] #50 androidconnect
  src/main/java/com/backend/simya/domain/chat/controller/ChatController.java
  src/main/java/com/backend/simya/domain/chat/dto/ChatMessageCustom.java
  src/main/java/com/backend/simya/domain/chat/dto/ChatRoom.java
  src/main/java/com/backend/simya/domain/chat/dto/ChatRoomForAndroid.java
  src/main/java/com/backend/simya/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/backend/simya/domain/chat/service/ChatService.java
  src/main/java/com/backend/simya/domain/chat/service/RedisPublisher.java
  src/main/java/com/backend/simya/domain/chat/service/RedisSubscriber.java
  src/main/java/com/backend/simya/domain/house/controller/HouseController.java
  src/main/java/com/backend/simya/domain/user/controller/UserController.java
  src/main/java/com/backend/simya/domain/user/dto/response/FormLoginResponseDto.java
  src/main/java/com/backend/simya/global/config/websocket/handler/StompHandler.java
Labels: feature, 왁
